# Generated by Django 3.1 on 2020-08-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('oid', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=100, verbose_name='fname')),
                ('mobile_no', models.IntegerField(default=' ', max_length=50, verbose_name='mobile_no')),
                ('address', models.CharField(max_length=200, verbose_name='address')),
                ('pin', models.IntegerField(default='', max_length=6, verbose_name='pin')),
                ('hno', models.CharField(max_length=50, verbose_name='hno')),
                ('city', models.CharField(max_length=50, verbose_name='city')),
                ('alt_no', models.IntegerField(default='', max_length=50, verbose_name='alt_no')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=70, verbose_name='pname')),
                ('price', models.IntegerField(verbose_name='price')),
                ('dicount', models.CharField(max_length=50, verbose_name='dicount')),
                ('sdesc', models.CharField(max_length=300, verbose_name='sdesc')),
                ('desc', models.CharField(max_length=1000, verbose_name='desc')),
                ('chat', models.CharField(max_length=50, verbose_name='chat')),
                ('subchat', models.CharField(max_length=50, verbose_name='subchat')),
                ('pimg', models.ImageField(default='', upload_to='shop1/images')),
            ],
        ),
        migrations.CreateModel(
            name='slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('stitle', models.CharField(max_length=120, verbose_name='stitle')),
                ('simg', models.ImageField(default='', upload_to='shop1/images')),
            ],
        ),
    ]
