# Generated by Django 3.1 on 2020-08-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop1', '0002_auto_20200817_0734'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('oid', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=100, verbose_name='fname')),
                ('mobile_no', models.IntegerField(max_length=50, verbose_name='mobile_no')),
                ('address', models.CharField(max_length=200, verbose_name='address')),
                ('pin', models.IntegerField(max_length=6, verbose_name='pin')),
                ('hno', models.CharField(max_length=50, verbose_name='hno')),
                ('city', models.CharField(max_length=50, verbose_name='city')),
                ('ostat', models.CharField(max_length=50, verbose_name='ostat')),
                ('alt_no', models.IntegerField(max_length=50, verbose_name='alt_no')),
            ],
        ),
        migrations.DeleteModel(
            name='orders',
        ),
    ]
