# Generated by Django 3.1 on 2020-08-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop1', '0003_auto_20200817_0735'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('oid', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=100, verbose_name='fname')),
                ('mobile_no', models.CharField(max_length=50, verbose_name='mobile_no')),
                ('address', models.CharField(max_length=200, verbose_name='address')),
                ('pin', models.IntegerField(default='', verbose_name='pin')),
                ('hno', models.CharField(max_length=50, verbose_name='hno')),
                ('city', models.CharField(max_length=50, verbose_name='city')),
                ('ostat', models.CharField(default='processing', max_length=50, verbose_name='ostat')),
                ('alt_no', models.CharField(max_length=50, verbose_name='alt_no')),
            ],
        ),
        migrations.DeleteModel(
            name='order',
        ),
        migrations.AddField(
            model_name='product',
            name='qnt',
            field=models.CharField(default='', max_length=50, verbose_name='qnt'),
        ),
    ]
