# Generated by Django 3.1 on 2020-08-25 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop1', '0010_auto_20200825_1056'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
