# Generated by Django 3.2 on 2021-04-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop1', '0012_auto_20200825_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pimg2',
            field=models.ImageField(blank=True, default='', null=True, upload_to='shop1/images'),
        ),
        migrations.AddField(
            model_name='product',
            name='pimg3',
            field=models.ImageField(blank=True, default='', null=True, upload_to='shop1/images'),
        ),
    ]
