# Generated by Django 3.2 on 2021-05-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop1', '0015_auto_20210409_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pimg2',
            field=models.ImageField(blank=True, default=1, null=True, upload_to='shop1/images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pimg3',
            field=models.ImageField(blank=True, default=1, null=True, upload_to='shop1/images'),
        ),
    ]
