# Generated by Django 3.2 on 2021-05-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop1', '0017_auto_20210502_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_argumented',
            field=models.CharField(default='no', max_length=3, verbose_name='is_argumented'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pimg2',
            field=models.ImageField(default=1, upload_to='shop1/images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pimg3',
            field=models.ImageField(default=1, upload_to='shop1/images'),
        ),
    ]
