# Generated by Django 3.2.3 on 2021-05-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop1', '0018_auto_20210502_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.ImageField(default='', upload_to='shop1/images/posters')),
                ('brand_name', models.CharField(default='', max_length=50)),
                ('disscount', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catgory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.ImageField(default='', upload_to='shop1/images/posters')),
                ('catgory_name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='soffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.ImageField(default='', upload_to='shop1/images/posters')),
                ('offer_name', models.CharField(default='', max_length=50)),
                ('disscount', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_argumented',
        ),
        migrations.AddField(
            model_name='product',
            name='is_avilable',
            field=models.CharField(default='no', max_length=3, verbose_name='is_argumented'),
        ),
    ]
