# Generated by Django 3.2.3 on 2021-05-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop1', '0019_auto_20210526_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='brands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.ImageField(default='', upload_to='shop1/images/posters')),
                ('brand_name', models.CharField(default='', max_length=50)),
                ('disscount', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
