# Generated by Django 3.2.3 on 2021-05-27 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop1', '0020_brands'),
    ]

    operations = [
        migrations.DeleteModel(
            name='brands',
        ),
    ]
