# Generated by Django 3.2.3 on 2021-06-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop1', '0022_alter_product_pimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='provider',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='provider'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='poster',
            field=models.ImageField(default='', height_field='100', upload_to='shop1/images/posters', width_field='100'),
        ),
        migrations.AlterField(
            model_name='catgory',
            name='poster',
            field=models.ImageField(default='', height_field='250', upload_to='shop1/images/posters', width_field='500'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pimg2',
            field=models.ImageField(default=1, height_field='600', upload_to='shop1/images', width_field='300'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pimg3',
            field=models.ImageField(default=1, height_field='600', upload_to='shop1/images', width_field='300'),
        ),
        migrations.AlterField(
            model_name='soffer',
            name='poster',
            field=models.ImageField(default='', height_field='100', upload_to='shop1/images/posters', width_field='100'),
        ),
    ]
