# Generated by Django 3.2.3 on 2021-06-06 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop1', '0025_auto_20210606_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pimg',
            new_name='image',
        ),
    ]
