# Generated by Django 3.2.3 on 2021-06-06 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop1', '0026_rename_pimg_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='pimg',
        ),
    ]
